
USE bases_datos;


CREATE TABLE IF NOT EXISTS uploadmenu (
    CATEGORY VARCHAR(255), 
    MENUITEM VARCHAR(255) ,    
    DISHOFFERS DECIMAL(10, 2),
    GENERALPRICE VARCHAR(255),
    ORDERCODE VARCHAR(255), 
    PRICE DECIMAL(10, 2)  
        
);

LOAD DATA INFILE 'C:\\xampp\\mysql\\data\\2024-09-10T19-00_export.csv'
INTO TABLE uploadmenu
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS
(CATEGORY, MENUITEM, DISHOFFERS, GENERALPRICE, ORDERCODE,PRICE);
